title: Arturo Herrero
title-weeknotes: Weeknotes | Arturo Herrero
description: The personal website of Arturo Herrero.
author: Arturo Herrero
url: "https://arturoherrero.com"

markdown: kramdown
permalink: :title/

collections:
  photos:
    output: true
    permalink: /photos/:title/
  weeknotes:
    output: true
    permalink: /weeknotes/:title/
  questions:
    output: true
    permalink: /questions/:title/

future: true

sass:
  style: :compressed
  sass_dir: assets/css

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

exclude:
  - .gitignore
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - vendor
